#Switches:
set_property PACKAGE_PIN W13 [get_ports {CinMeat}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CinMeat}]
set_property PACKAGE_PIN V2 [get_ports {BMeat[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {BMeat[3]}]
set_property PACKAGE_PIN T3 [get_ports {BMeat[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {BMeat[2]}]
set_property PACKAGE_PIN T2 [get_ports {BMeat[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {BMeat[1]}]
set_property PACKAGE_PIN R3 [get_ports {BMeat[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {BMeat[0]}]
set_property PACKAGE_PIN W2 [get_ports {AMeat[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AMeat[3]}]
set_property PACKAGE_PIN U1 [get_ports {AMeat[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AMeat[2]}]
set_property PACKAGE_PIN T1 [get_ports {AMeat[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AMeat[1]}]
set_property PACKAGE_PIN R2 [get_ports {AMeat[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AMeat[0]}]
 

#LEDs:
set_property PACKAGE_PIN U16 [get_ports {CoutMeat}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CoutMeat}]
set_property PACKAGE_PIN P3 [get_ports {SMeat[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SMeat[3]}]
set_property PACKAGE_PIN N3 [get_ports {SMeat[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SMeat[2]}]
set_property PACKAGE_PIN P1 [get_ports {SMeat[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SMeat[1]}]
set_property PACKAGE_PIN L1 [get_ports {SMeat[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SMeat[0]}]
